name: adam_can_play_any_strategy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # - attrs=19.3.0=py_0
  # - bidict=0.20.0=py_0
  # - bleach=3.1.5=py_0
  # - ca-certificates=2020.6.24=0
  # - certifi=2020.6.20=py36_0
  # - decorator=4.4.2=py_0
  # - defusedxml=0.6.0=py_0
  # - entrypoints=0.3=py36_0
  # - importlib-metadata=1.6.1=py36_0
  # - importlib_metadata=1.6.1=0
  # - joblib=0.16.0=py_0
  # - more-itertools=8.4.0=py_0
  # - packaging=20.4=py_0
  # - pip=20.1.1=py36_1
  # - pluggy=0.13.1=py36_0
  # - ply=3.11=py36_0
  # - py=1.8.2=py_0
  # - pyparsing=2.4.7=py_0
  # - pytest=5.4.3=py36_0
  # - python_abi=3.6=1_cp36m
  # - setuptools=47.3.0=py36_0
  # - six=1.15.0=py_0
  # - tqdm=4.47.0=py_0
  # - wcwidth=0.2.4=py_0
  # - wheel=0.34.2=py36_0
  # - zipp=3.1.0=py_0
  - pip:
    - cloudpickle
    - cycler
    - future
    - matplotlib
    - mpmath
    - networkx
    - numpy
    - pandas
    - pybullet
    - pydot
    - pydot3
    - pyglet
    - pygraphviz
    - pyperplan
    - graphviz
    - pytz
    - pyyaml
    - scipy
    - gym
    - gym_minigrid
    - ply
    - bidict
    - joblib
    - ipython
    - tqdm
    - shapely
    - docker
    - paramiko
    - pydot
    # - cloudpickle==1.3.0
    # - cycler==0.10.0
    # - future==0.18.2
    # - matplotlib
    # - mpmath==1.1.0
    # - networkx==2.4
    # - numpy==1.18.2
    # - pandas==1.0.3
    # - pybullet==3.0.8
    # - pydot==1.4.1
    # - pydot3==1.0.9
    # - pyglet==1.5.0
    # - pygraphviz==1.5
    # - pyperplan==1.3
    # - graphviz==0.14
    # - pytz==2019.3
    # - pyyaml==5.3.1
    # - scipy==1.4.1
