name: adam_can_play_any_strategy
channels:
  - defaults
dependencies:
    - pyyaml
    - numpy
    - bidict
    - networkx
    - python-graphviz  # installs graphivz as well
    - ply
    - cloudpickle
    - cycler
    - future
    - matplotlib
    - mpmath
    - pandas
    - pybullet
    - pydot
    - pydot3
    - pyglet
    - pyperplan
    - pytz
    - scipy
    - gym
    - gym_minigrid
    - joblib
    - ipython
    - tqdm
    - shapely
    - docker
    - paramiko
