graph:
  edges:
  - !!python/tuple
    - &id001 !!python/tuple
      - v1
      - '1'
    - &id002 !!python/tuple
      - v2
      - '1'
    - weight: '1'
  - !!python/tuple
    - *id001
    - &id004 !!python/tuple
      - v3
      - '1'
    - weight: '1'
  - !!python/tuple
    - &id003 !!python/tuple
      - v1
      - '-1'
    - *id002
    - weight: '1'
  - !!python/tuple
    - *id003
    - *id004
    - weight: '1'
  - !!python/tuple
    - &id005 !!python/tuple
      - v1
      - '2'
    - &id011 !!python/tuple
      - v2
      - '2'
    - weight: '2'
  - !!python/tuple
    - *id005
    - &id012 !!python/tuple
      - v3
      - '2'
    - weight: '2'
  - !!python/tuple
    - &id006 !!python/tuple
      - v1
      - '0.5'
    - *id002
    - weight: '1'
  - !!python/tuple
    - *id006
    - *id004
    - weight: '1'
  - !!python/tuple
    - &id007 !!python/tuple
      - v1
      - '0'
    - *id002
    - weight: '1'
  - !!python/tuple
    - *id007
    - *id004
    - weight: '1'
  - !!python/tuple
    - &id008 !!python/tuple
      - v1
      - '6'
    - &id015 !!python/tuple
      - v2
      - '6'
    - weight: '6'
  - !!python/tuple
    - *id008
    - &id016 !!python/tuple
      - v3
      - '6'
    - weight: '6'
  - !!python/tuple
    - *id002
    - *id001
    - weight: '1'
  - !!python/tuple
    - *id002
    - *id004
    - weight: '1'
  - !!python/tuple
    - *id002
    - &id010 !!python/tuple
      - v4
      - '2'
    - weight: '2'
  - !!python/tuple
    - &id009 !!python/tuple
      - v2
      - '-1'
    - *id003
    - weight: '-1'
  - !!python/tuple
    - *id009
    - *id004
    - weight: '1'
  - !!python/tuple
    - *id009
    - *id010
    - weight: '2'
  - !!python/tuple
    - *id011
    - *id005
    - weight: '2'
  - !!python/tuple
    - *id011
    - *id012
    - weight: '2'
  - !!python/tuple
    - *id011
    - *id010
    - weight: '2'
  - !!python/tuple
    - &id013 !!python/tuple
      - v2
      - '0.5'
    - *id006
    - weight: '0.5'
  - !!python/tuple
    - *id013
    - *id004
    - weight: '1'
  - !!python/tuple
    - *id013
    - *id010
    - weight: '2'
  - !!python/tuple
    - &id014 !!python/tuple
      - v2
      - '0'
    - *id007
    - weight: '0'
  - !!python/tuple
    - *id014
    - *id004
    - weight: '1'
  - !!python/tuple
    - *id014
    - *id010
    - weight: '2'
  - !!python/tuple
    - *id015
    - *id008
    - weight: '6'
  - !!python/tuple
    - *id015
    - *id016
    - weight: '6'
  - !!python/tuple
    - *id015
    - &id025 !!python/tuple
      - v4
      - '6'
    - weight: '6'
  - !!python/tuple
    - *id004
    - *id004
    - weight: '1'
  - !!python/tuple
    - *id004
    - &id018 !!python/tuple
      - v5
      - '1'
    - weight: '1'
  - !!python/tuple
    - &id017 !!python/tuple
      - v3
      - '-1'
    - &id019 !!python/tuple
      - v3
      - '0.5'
    - weight: '0.5'
  - !!python/tuple
    - *id017
    - *id018
    - weight: '1'
  - !!python/tuple
    - *id012
    - *id012
    - weight: '2'
  - !!python/tuple
    - *id012
    - &id027 !!python/tuple
      - v5
      - '2'
    - weight: '2'
  - !!python/tuple
    - *id019
    - *id019
    - weight: '0.5'
  - !!python/tuple
    - *id019
    - *id018
    - weight: '1'
  - !!python/tuple
    - &id020 !!python/tuple
      - v3
      - '0'
    - *id019
    - weight: '0.5'
  - !!python/tuple
    - *id020
    - *id018
    - weight: '1'
  - !!python/tuple
    - *id016
    - *id016
    - weight: '6'
  - !!python/tuple
    - *id016
    - &id030 !!python/tuple
      - v5
      - '6'
    - weight: '6'
  - !!python/tuple
    - &id021 !!python/tuple
      - v4
      - '1'
    - *id001
    - weight: '1'
  - !!python/tuple
    - *id021
    - *id010
    - weight: '2'
  - !!python/tuple
    - &id022 !!python/tuple
      - v4
      - '-1'
    - *id007
    - weight: '0'
  - !!python/tuple
    - *id022
    - *id010
    - weight: '2'
  - !!python/tuple
    - *id010
    - *id005
    - weight: '2'
  - !!python/tuple
    - *id010
    - *id010
    - weight: '2'
  - !!python/tuple
    - &id023 !!python/tuple
      - v4
      - '0.5'
    - *id006
    - weight: '0.5'
  - !!python/tuple
    - *id023
    - *id010
    - weight: '2'
  - !!python/tuple
    - &id024 !!python/tuple
      - v4
      - '0'
    - *id007
    - weight: '0'
  - !!python/tuple
    - *id024
    - *id010
    - weight: '2'
  - !!python/tuple
    - *id025
    - *id008
    - weight: '6'
  - !!python/tuple
    - *id025
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id018
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id018
    - *id018
    - weight: '1'
  - !!python/tuple
    - &id026 !!python/tuple
      - v5
      - '-1'
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id026
    - *id018
    - weight: '1'
  - !!python/tuple
    - *id027
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id027
    - *id027
    - weight: '2'
  - !!python/tuple
    - &id028 !!python/tuple
      - v5
      - '0.5'
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id028
    - *id018
    - weight: '1'
  - !!python/tuple
    - &id029 !!python/tuple
      - v5
      - '0'
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id029
    - *id018
    - weight: '1'
  - !!python/tuple
    - *id030
    - *id025
    - weight: '6'
  - !!python/tuple
    - *id030
    - *id030
    - weight: '6'
  vertices:
  - !!python/tuple
    - *id001
    - player: eve
  - !!python/tuple
    - *id003
    - player: eve
  - !!python/tuple
    - *id005
    - player: eve
  - !!python/tuple
    - *id006
    - player: eve
  - !!python/tuple
    - *id007
    - player: eve
  - !!python/tuple
    - *id008
    - init: true
      player: eve
  - !!python/tuple
    - *id002
    - player: adam
  - !!python/tuple
    - *id009
    - player: adam
  - !!python/tuple
    - *id011
    - player: adam
  - !!python/tuple
    - *id013
    - player: adam
  - !!python/tuple
    - *id014
    - player: adam
  - !!python/tuple
    - *id015
    - player: adam
  - !!python/tuple
    - *id004
    - player: adam
  - !!python/tuple
    - *id017
    - player: adam
  - !!python/tuple
    - *id012
    - player: adam
  - !!python/tuple
    - *id019
    - player: adam
  - !!python/tuple
    - *id020
    - player: adam
  - !!python/tuple
    - *id016
    - player: adam
  - !!python/tuple
    - *id021
    - player: eve
  - !!python/tuple
    - *id022
    - player: eve
  - !!python/tuple
    - *id010
    - player: eve
  - !!python/tuple
    - *id023
    - player: eve
  - !!python/tuple
    - *id024
    - player: eve
  - !!python/tuple
    - *id025
    - player: eve
  - !!python/tuple
    - *id018
    - player: eve
  - !!python/tuple
    - *id026
    - player: eve
  - !!python/tuple
    - *id027
    - player: eve
  - !!python/tuple
    - *id028
    - player: eve
  - !!python/tuple
    - *id029
    - player: eve
  - !!python/tuple
    - *id030
    - player: eve
