graph:
  edges:
  - !!python/tuple
    - 1
    - 2
    - weight: 1
  - !!python/tuple
    - 1
    - 3
    - weight: 1
  - !!python/tuple
    - 2
    - 1
    - weight: -1
  - !!python/tuple
    - 3
    - 3
    - weight: 0.5
  vertices:
  - !!python/tuple
    - 1
    - player: eve
  - !!python/tuple
    - 2
    - player: adam
  - !!python/tuple
    - 3
    - player: adam
