graph:
  edges:
  - !!python/tuple
    - 1
    - 2
    - weight: 1
  - !!python/tuple
    - 1
    - 3
    - weight: 1
  - !!python/tuple
    - 2
    - 1
    - weight: -1
  - !!python/tuple
    - 2
    - 4
    - weight: 2
  - !!python/tuple
    - 3
    - 3
    - weight: 0.5
  - !!python/tuple
    - 3
    - 5
    - weight: 1
  - !!python/tuple
    - 4
    - 4
    - weight: 2
  - !!python/tuple
    - 5
    - 5
    - weight: 1
  vertices:
  - !!python/tuple
    - 1
    - init: true
      player: eve
  - !!python/tuple
    - 2
    - player: adam
  - !!python/tuple
    - 3
    - player: adam
  - !!python/tuple
    - 4
    - player: eve
  - !!python/tuple
    - 5
    - player: eve
