alphabet_size: 3
edges:
- !!python/tuple
  - accept_all
  - accept_all
  - guard: !!python/object:src.spot.Parser.TrueExpression
      formula: '1'
    guard_formula: '1'
- !!python/tuple
  - T0_init
  - accept_all
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (goal_green_open)
      name: goal_green_open
      symbol: goal_green_open
    guard_formula: (goal_green_open)
- !!python/tuple
  - T0_init
  - T0_init
  - guard: !!python/object:src.spot.Parser.NotSymbolExpression
      formula: (!(goal_green_open))
      name: '!goal_green_open'
      symbol: goal_green_open
    guard_formula: (!(goal_green_open))
nodes:
- !!python/tuple
  - accept_all
  - accepting: true
- !!python/tuple
  - T0_init
  - init: true
num_obs: 3
num_states: 2
start_state: T0_init
