graph:
  edges:
  - !!python/tuple
    - accept_all
    - accept_all
    - guard: !!python/object:src.spot.Parser.TrueExpression
        formula: '1'
      guard_formula: '1'
  - !!python/tuple
    - T0_S2
    - T0_S2
    - guard: !!python/object:src.spot.Parser.SymbolExpression
        formula: (true)
        name: 'true'
        symbol: 'true'
      guard_formula: (true)
  - !!python/tuple
    - T0_init
    - accept_all
    - guard: !!python/object:src.spot.Parser.SymbolExpression
        formula: (c)
        name: c
        symbol: c
      guard_formula: (c)
  - !!python/tuple
    - T0_init
    - T0_init
    - guard: !!python/object:src.spot.Parser.ANDExpression
        formula: ((!(b)) && (!(c)))
        left: !!python/object:src.spot.Parser.NotSymbolExpression
          name: '!b'
          symbol: b
        right: !!python/object:src.spot.Parser.NotSymbolExpression
          name: '!c'
          symbol: c
      guard_formula: ((!(b)) && (!(c)))
  - !!python/tuple
    - T0_init
    - T0_S2
    - guard: !!python/object:src.spot.Parser.ANDExpression
        formula: ((b) && (!(c)))
        left: !!python/object:src.spot.Parser.SymbolExpression
          name: b
          symbol: b
        right: !!python/object:src.spot.Parser.NotSymbolExpression
          name: '!c'
          symbol: c
      guard_formula: ((b) && (!(c)))
  vertices:
  - !!python/tuple
    - accept_all
    - accepting: true
  - !!python/tuple
    - T0_S2
    - {}
  - !!python/tuple
    - T0_init
    - init: true
