alphabet_size: 14
edges:
- !!python/tuple
  - v1
  - v2
  - strategy: true
    weight: 1
- !!python/tuple
  - v2
  - v3
  - strategy: true
    weight: 0
- !!python/tuple
  - v2
  - v9
  - strategy: false
    weight: 0
- !!python/tuple
  - v3
  - v4
  - strategy: true
    weight: 1
- !!python/tuple
  - v3
  - v2
  - strategy: false
    weight: 1
- !!python/tuple
  - v3
  - v6
  - strategy: false
    weight: 6
- !!python/tuple
  - v4
  - v5
  - strategy: true
    weight: 0
- !!python/tuple
  - v4
  - v9
  - strategy: false
    weight: 0
- !!python/tuple
  - v5
  - v6
  - strategy: true
    weight: 3
- !!python/tuple
  - v5
  - v4
  - strategy: false
    weight: 1
- !!python/tuple
  - v6
  - v9
  - strategy: true
    weight: 0
- !!python/tuple
  - v9
  - v12
  - strategy: true
    weight: 0
- !!python/tuple
  - v12
  - v12
  - strategy: true
    weight: 0
- !!python/tuple
  - tmp_accp
  - tmp_accp
  - strategy: false
    weight: 0
nodes:
- !!python/tuple
  - v1
  - init: true
    player: eve
- !!python/tuple
  - v2
  - player: adam
- !!python/tuple
  - v3
  - player: eve
- !!python/tuple
  - v4
  - player: adam
- !!python/tuple
  - v5
  - player: eve
- !!python/tuple
  - v6
  - player: adam
- !!python/tuple
  - v9
  - player: eve
- !!python/tuple
  - v12
  - player: eve
- !!python/tuple
  - tmp_accp
  - accepting: true
    player: eve
num_obs: 3
num_states: 9
start_state: v1
