alphabet_size: 48
edges:
- !!python/tuple
  - v0
  - v0
  - strategy: true
    weight: '0'
- !!python/tuple
  - v0
  - v1
  - strategy: false
    weight: '0'
- !!python/tuple
  - v1
  - &id002 !!python/tuple
    - &id001 !!python/tuple
      - !!python/tuple
        - (1, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: 0
- !!python/tuple
  - v1
  - &id018 !!python/tuple
    - *id001
    - -4.0
  - strategy: false
    weight: 0
- !!python/tuple
  - vT
  - vT
  - strategy: true
    weight: '-9.0'
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id002
  - !!python/tuple
    - &id003 !!python/tuple
      - !!python/tuple
        - (1, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-2.0'
- !!python/tuple
  - *id002
  - !!python/tuple
    - &id005 !!python/tuple
      - !!python/tuple
        - (2, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-3.0'
- !!python/tuple
  - &id019 !!python/tuple
    - accept_all
    - 0.0
  - !!python/tuple
    - accept_all
    - 0.0
  - strategy: true
    weight: '0.0'
- !!python/tuple
  - &id020 !!python/tuple
    - T0_S2
    - 0.0
  - !!python/tuple
    - T0_S2
    - 0.0
  - strategy: true
    weight: '-4.0'
- !!python/tuple
  - &id004 !!python/tuple
    - *id003
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id004
  - !!python/tuple
    - &id007 !!python/tuple
      - !!python/tuple
        - (1, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-2.0'
- !!python/tuple
  - *id004
  - !!python/tuple
    - &id009 !!python/tuple
      - !!python/tuple
        - (2, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-3.0'
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id006 !!python/tuple
    - *id005
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-2.0'
- !!python/tuple
  - *id006
  - !!python/tuple
    - &id011 !!python/tuple
      - !!python/tuple
        - (3, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-3.0'
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id008 !!python/tuple
    - *id007
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-2.0'
- !!python/tuple
  - *id008
  - !!python/tuple
    - &id013 !!python/tuple
      - !!python/tuple
        - (2, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-3.0'
- !!python/tuple
  - &id010 !!python/tuple
    - *id009
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-2.0'
- !!python/tuple
  - *id010
  - !!python/tuple
    - &id015 !!python/tuple
      - !!python/tuple
        - (3, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-3.0'
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id012 !!python/tuple
    - *id011
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (3, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (3, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-2.0'
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id014 !!python/tuple
    - *id013
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-2.0'
- !!python/tuple
  - *id014
  - !!python/tuple
    - &id017 !!python/tuple
      - !!python/tuple
        - (3, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-3.0'
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (1, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id016 !!python/tuple
    - *id015
    - 0.0
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (3, 1), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-1.0'
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (3, 3), right
        - 0
      - T0_init
    - 0.0
  - strategy: true
    weight: '-2.0'
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (3, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-3.0'
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - (2, 2), right
        - 0
      - T0_init
    - 0.0
  - strategy: false
    weight: '-4.0'
- !!python/tuple
  - &id021 !!python/tuple
    - *id017
    - 0.0
  - !!python/tuple
    - accept_all
    - 0.0
  - strategy: true
    weight: '0.0'
- !!python/tuple
  - *id018
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id022 !!python/tuple
    - accept_all
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id023 !!python/tuple
    - T0_S2
    - -4.0
  - !!python/tuple
    - T0_S2
    - -4.0
  - strategy: true
    weight: '0.0'
- !!python/tuple
  - &id024 !!python/tuple
    - *id003
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id025 !!python/tuple
    - *id005
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id026 !!python/tuple
    - *id007
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id027 !!python/tuple
    - *id009
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id028 !!python/tuple
    - *id011
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id029 !!python/tuple
    - *id013
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id030 !!python/tuple
    - *id015
    - -4.0
  - vT
  - strategy: true
    weight: 0
- !!python/tuple
  - &id031 !!python/tuple
    - *id017
    - -4.0
  - vT
  - strategy: true
    weight: 0
nodes:
- !!python/tuple
  - v0
  - init: true
    player: adam
- !!python/tuple
  - v1
  - player: eve
- !!python/tuple
  - vT
  - player: eve
- !!python/tuple
  - *id002
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id019
  - accepting: true
    ap: null
    player: eve
- !!python/tuple
  - *id020
  - ap: null
    player: eve
- !!python/tuple
  - *id004
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id006
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id008
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id010
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id012
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id014
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id016
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id021
  - ap: goal_green_open
    player: eve
- !!python/tuple
  - *id018
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id022
  - accepting: true
    ap: null
    player: eve
- !!python/tuple
  - *id023
  - ap: null
    player: eve
- !!python/tuple
  - *id024
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id025
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id026
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id027
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id028
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id029
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id030
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - *id031
  - ap: goal_green_open
    player: eve
num_obs: 3
num_states: 25
start_state: v0
