graph:
  edges:
  - !!python/tuple
    - v0
    - v0
    - strategy: false
      weight: '0'
  - !!python/tuple
    - v0
    - v1
    - strategy: true
      weight: '0'
  - !!python/tuple
    - v1
    - &id005 !!python/tuple
      - &id001 !!python/tuple
        - !!python/tuple
          - s2
          - 0
        - T0_init
      - 0.0
    - strategy: true
      weight: 0
  - !!python/tuple
    - v1
    - &id026 !!python/tuple
      - *id001
      - -5.0
    - strategy: false
      weight: 0
  - !!python/tuple
    - vT
    - vT
    - strategy: true
      weight: '-11.0'
  - !!python/tuple
    - &id041 !!python/tuple
      - accept_all
      - 0.0
    - !!python/tuple
      - accept_all
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - &id042 !!python/tuple
      - &id011 !!python/tuple
        - !!python/tuple
          - s1
          - 0
        - T0_init
      - 0.0
    - !!python/tuple
      - T0_S2
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - &id002 !!python/tuple
      - &id012 !!python/tuple
        - !!python/tuple
          - h12
          - '0'
        - T0_init
      - 0.0
    - !!python/tuple
      - &id013 !!python/tuple
        - !!python/tuple
          - s2
          - 0
        - T0_init
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - &id015 !!python/tuple
        - !!python/tuple
          - s3
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - &id016 !!python/tuple
        - !!python/tuple
          - s1
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id043 !!python/tuple
      - T0_S2
      - 0.0
    - !!python/tuple
      - T0_S2
      - 0.0
    - strategy: true
      weight: '-5.0'
  - !!python/tuple
    - &id003 !!python/tuple
      - &id017 !!python/tuple
        - !!python/tuple
          - h13
          - '0'
        - T0_init
      - 0.0
    - !!python/tuple
      - &id018 !!python/tuple
        - !!python/tuple
          - s3
          - 0
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - &id020 !!python/tuple
        - !!python/tuple
          - s2
          - 1
        - T0_init
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - &id021 !!python/tuple
        - !!python/tuple
          - s1
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id044 !!python/tuple
      - &id022 !!python/tuple
        - !!python/tuple
          - s1
          - 1
        - T0_init
      - 0.0
    - !!python/tuple
      - T0_S2
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - &id004 !!python/tuple
      - &id023 !!python/tuple
        - !!python/tuple
          - s2
          - 1
        - T0_init
      - 0.0
    - !!python/tuple
      - !!python/tuple
        - !!python/tuple
          - s1
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '2.0'
  - !!python/tuple
    - *id004
    - !!python/tuple
      - &id024 !!python/tuple
        - !!python/tuple
          - s3
          - 1
        - T0_init
      - 0.0
    - strategy: true
      weight: '3.0'
  - !!python/tuple
    - &id045 !!python/tuple
      - &id025 !!python/tuple
        - !!python/tuple
          - s3
          - 1
        - T0_init
      - 0.0
    - !!python/tuple
      - accept_all
      - 0.0
    - strategy: true
      weight: '5.0'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - &id006 !!python/tuple
        - !!python/tuple
          - h21
          - '0'
        - T0_init
      - 0.0
    - strategy: false
      weight: '2.0'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - &id008 !!python/tuple
        - !!python/tuple
          - h23
          - '0'
        - T0_init
      - 0.0
    - strategy: true
      weight: '3.0'
  - !!python/tuple
    - &id007 !!python/tuple
      - *id006
      - 0.0
    - !!python/tuple
      - &id027 !!python/tuple
        - !!python/tuple
          - s1
          - 0
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id007
    - !!python/tuple
      - &id029 !!python/tuple
        - !!python/tuple
          - s3
          - 1
        - T0_init
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - *id007
    - !!python/tuple
      - &id030 !!python/tuple
        - !!python/tuple
          - s2
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id009 !!python/tuple
      - *id008
      - 0.0
    - !!python/tuple
      - &id031 !!python/tuple
        - !!python/tuple
          - s3
          - 0
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - &id033 !!python/tuple
        - !!python/tuple
          - s2
          - 1
        - T0_init
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - &id034 !!python/tuple
        - !!python/tuple
          - s1
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id046 !!python/tuple
      - &id035 !!python/tuple
        - !!python/tuple
          - s3
          - 0
        - T0_init
      - 0.0
    - !!python/tuple
      - accept_all
      - 0.0
    - strategy: true
      weight: '5.0'
  - !!python/tuple
    - &id010 !!python/tuple
      - &id036 !!python/tuple
        - !!python/tuple
          - h31
          - '0'
        - T0_init
      - 0.0
    - !!python/tuple
      - &id037 !!python/tuple
        - !!python/tuple
          - s1
          - 0
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - &id039 !!python/tuple
        - !!python/tuple
          - s3
          - 1
        - T0_init
      - 0.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - &id040 !!python/tuple
        - !!python/tuple
          - s2
          - 1
        - T0_init
      - 0.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - &id047 !!python/tuple
      - accept_all
      - -5.0
    - vT
    - strategy: false
      weight: 0
  - !!python/tuple
    - &id048 !!python/tuple
      - *id011
      - -5.0
    - !!python/tuple
      - T0_S2
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id014 !!python/tuple
      - *id012
      - -5.0
    - !!python/tuple
      - *id013
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - *id015
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - *id016
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id049 !!python/tuple
      - T0_S2
      - -5.0
    - !!python/tuple
      - T0_S2
      - -5.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id019 !!python/tuple
      - *id017
      - -5.0
    - !!python/tuple
      - *id018
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - *id020
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - *id021
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id050 !!python/tuple
      - *id022
      - -5.0
    - !!python/tuple
      - T0_S2
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id051 !!python/tuple
      - *id023
      - -5.0
    - !!python/tuple
      - *id024
      - -5.0
    - strategy: false
      weight: '8.0'
  - !!python/tuple
    - &id052 !!python/tuple
      - *id025
      - -5.0
    - vT
    - strategy: false
      weight: 0
  - !!python/tuple
    - *id026
    - vT
    - strategy: false
      weight: 0
  - !!python/tuple
    - &id028 !!python/tuple
      - *id006
      - -5.0
    - !!python/tuple
      - *id027
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id028
    - !!python/tuple
      - *id029
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id028
    - !!python/tuple
      - *id030
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id032 !!python/tuple
      - *id008
      - -5.0
    - !!python/tuple
      - *id031
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id032
    - !!python/tuple
      - *id033
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id032
    - !!python/tuple
      - *id034
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - &id053 !!python/tuple
      - *id035
      - -5.0
    - vT
    - strategy: false
      weight: 0
  - !!python/tuple
    - &id038 !!python/tuple
      - *id036
      - -5.0
    - !!python/tuple
      - *id037
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id038
    - !!python/tuple
      - *id039
      - -5.0
    - strategy: false
      weight: '5.0'
  - !!python/tuple
    - *id038
    - !!python/tuple
      - *id040
      - -5.0
    - strategy: false
      weight: '5.0'
  vertices:
  - !!python/tuple
    - v0
    - init: true
      player: adam
  - !!python/tuple
    - v1
    - player: eve
  - !!python/tuple
    - vT
    - player: eve
  - !!python/tuple
    - *id041
    - accepting: true
      player: eve
  - !!python/tuple
    - *id042
    - player: eve
  - !!python/tuple
    - *id002
    - player: adam
  - !!python/tuple
    - *id043
    - player: eve
  - !!python/tuple
    - *id003
    - player: adam
  - !!python/tuple
    - *id044
    - player: eve
  - !!python/tuple
    - *id004
    - player: eve
  - !!python/tuple
    - *id045
    - player: eve
  - !!python/tuple
    - *id005
    - player: eve
  - !!python/tuple
    - *id007
    - player: adam
  - !!python/tuple
    - *id009
    - player: adam
  - !!python/tuple
    - *id046
    - player: eve
  - !!python/tuple
    - *id010
    - player: adam
  - !!python/tuple
    - *id047
    - accepting: true
      player: eve
  - !!python/tuple
    - *id048
    - player: eve
  - !!python/tuple
    - *id014
    - player: adam
  - !!python/tuple
    - *id049
    - player: eve
  - !!python/tuple
    - *id019
    - player: adam
  - !!python/tuple
    - *id050
    - player: eve
  - !!python/tuple
    - *id051
    - player: eve
  - !!python/tuple
    - *id052
    - player: eve
  - !!python/tuple
    - *id026
    - player: eve
  - !!python/tuple
    - *id028
    - player: adam
  - !!python/tuple
    - *id032
    - player: adam
  - !!python/tuple
    - *id053
    - player: eve
  - !!python/tuple
    - *id038
    - player: adam
