graph:
  edges:
  - !!python/tuple
    - v1
    - v32
    - weight: '3'
  - !!python/tuple
    - v2
    - v3
    - weight: '3'
  - !!python/tuple
    - v2
    - v8
    - weight: '0'
  - !!python/tuple
    - v2
    - v10
    - weight: '0'
  - !!python/tuple
    - v3
    - v14
    - weight: '6'
  - !!python/tuple
    - v3
    - v16
    - weight: '1'
  - !!python/tuple
    - v4
    - v1
    - weight: '6'
  - !!python/tuple
    - v4
    - v9
    - weight: '0'
  - !!python/tuple
    - v4
    - v10
    - weight: '0'
  - !!python/tuple
    - v5
    - v27
    - weight: '1'
  - !!python/tuple
    - v6
    - v5
    - weight: '1'
  - !!python/tuple
    - v6
    - v8
    - weight: '0'
  - !!python/tuple
    - v6
    - v9
    - weight: '0'
  - !!python/tuple
    - v7
    - v5
    - weight: '1'
  - !!python/tuple
    - v7
    - v8
    - weight: '0'
  - !!python/tuple
    - v7
    - v9
    - weight: '0'
  - !!python/tuple
    - v8
    - v39
    - weight: '3'
  - !!python/tuple
    - v9
    - v8
    - weight: '6'
  - !!python/tuple
    - v9
    - v20
    - weight: '1'
  - !!python/tuple
    - v10
    - v30
    - weight: '1'
  - !!python/tuple
    - v11
    - v12
    - weight: '3'
  - !!python/tuple
    - v12
    - v13
    - weight: '3'
  - !!python/tuple
    - v12
    - v18
    - weight: '0'
  - !!python/tuple
    - v12
    - v20
    - weight: '0'
  - !!python/tuple
    - v13
    - v16
    - weight: '1'
  - !!python/tuple
    - v13
    - v14
    - weight: '6'
  - !!python/tuple
    - v14
    - v11
    - weight: '3'
  - !!python/tuple
    - v14
    - v19
    - weight: '0'
  - !!python/tuple
    - v14
    - v20
    - weight: '0'
  - !!python/tuple
    - v15
    - v27
    - weight: '1'
  - !!python/tuple
    - v16
    - v15
    - weight: '1'
  - !!python/tuple
    - v16
    - v18
    - weight: '0'
  - !!python/tuple
    - v16
    - v19
    - weight: '0'
  - !!python/tuple
    - v17
    - v15
    - weight: '1'
  - !!python/tuple
    - v17
    - v18
    - weight: '0'
  - !!python/tuple
    - v17
    - v19
    - weight: '0'
  - !!python/tuple
    - v18
    - v19
    - weight: '3'
  - !!python/tuple
    - v19
    - v18
    - weight: '6'
  - !!python/tuple
    - v19
    - v20
    - weight: '1'
  - !!python/tuple
    - v20
    - v30
    - weight: '1'
  - !!python/tuple
    - v21
    - v22
    - weight: '3'
  - !!python/tuple
    - v22
    - v23
    - weight: '3'
  - !!python/tuple
    - v22
    - v28
    - weight: '0'
  - !!python/tuple
    - v22
    - v30
    - weight: '0'
  - !!python/tuple
    - v23
    - v26
    - weight: '1'
  - !!python/tuple
    - v23
    - v24
    - weight: '6'
  - !!python/tuple
    - v24
    - v21
    - weight: '6'
  - !!python/tuple
    - v24
    - v29
    - weight: '0'
  - !!python/tuple
    - v24
    - v30
    - weight: '0'
  - !!python/tuple
    - v25
    - v27
    - weight: '1'
  - !!python/tuple
    - v26
    - v25
    - weight: '1'
  - !!python/tuple
    - v26
    - v28
    - weight: '0'
  - !!python/tuple
    - v26
    - v29
    - weight: '0'
  - !!python/tuple
    - v27
    - v25
    - weight: '1'
  - !!python/tuple
    - v27
    - v28
    - weight: '0'
  - !!python/tuple
    - v27
    - v29
    - weight: '0'
  - !!python/tuple
    - v28
    - v29
    - weight: '3'
  - !!python/tuple
    - v29
    - v28
    - weight: '6'
  - !!python/tuple
    - v29
    - v30
    - weight: '1'
  - !!python/tuple
    - v30
    - v30
    - weight: '1'
  - !!python/tuple
    - v31
    - v32
    - weight: '3'
  - !!python/tuple
    - v32
    - v33
    - weight: '3'
  - !!python/tuple
    - v32
    - v38
    - weight: '0'
  - !!python/tuple
    - v32
    - v40
    - weight: '0'
  - !!python/tuple
    - v33
    - v36
    - weight: '1'
  - !!python/tuple
    - v33
    - v34
    - weight: '6'
  - !!python/tuple
    - v34
    - v31
    - weight: '6'
  - !!python/tuple
    - v34
    - v39
    - weight: '0'
  - !!python/tuple
    - v34
    - v40
    - weight: '0'
  - !!python/tuple
    - v35
    - v37
    - weight: '1'
  - !!python/tuple
    - v36
    - v35
    - weight: '1'
  - !!python/tuple
    - v36
    - v38
    - weight: '0'
  - !!python/tuple
    - v36
    - v39
    - weight: '0'
  - !!python/tuple
    - v37
    - v35
    - weight: '1'
  - !!python/tuple
    - v37
    - v38
    - weight: '0'
  - !!python/tuple
    - v37
    - v39
    - weight: '0'
  - !!python/tuple
    - v38
    - v39
    - weight: '3'
  - !!python/tuple
    - v39
    - v38
    - weight: '6'
  - !!python/tuple
    - v39
    - v40
    - weight: '1'
  - !!python/tuple
    - v40
    - v40
    - weight: '1'
  vertices:
  - !!python/tuple
    - v1
    - player: eve
  - !!python/tuple
    - v2
    - player: adam
  - !!python/tuple
    - v3
    - init: true
      player: eve
  - !!python/tuple
    - v4
    - player: adam
  - !!python/tuple
    - v5
    - player: eve
  - !!python/tuple
    - v6
    - player: adam
  - !!python/tuple
    - v7
    - player: adam
  - !!python/tuple
    - v8
    - player: eve
  - !!python/tuple
    - v9
    - player: eve
  - !!python/tuple
    - v10
    - player: eve
  - !!python/tuple
    - v11
    - player: eve
  - !!python/tuple
    - v12
    - player: adam
  - !!python/tuple
    - v13
    - player: eve
  - !!python/tuple
    - v14
    - player: adam
  - !!python/tuple
    - v15
    - player: eve
  - !!python/tuple
    - v16
    - player: adam
  - !!python/tuple
    - v17
    - player: adam
  - !!python/tuple
    - v18
    - player: eve
  - !!python/tuple
    - v19
    - player: eve
  - !!python/tuple
    - v20
    - player: eve
  - !!python/tuple
    - v21
    - accepting: true
      player: eve
  - !!python/tuple
    - v22
    - accepting: true
      player: adam
  - !!python/tuple
    - v23
    - accepting: true
      player: eve
  - !!python/tuple
    - v24
    - accepting: true
      player: adam
  - !!python/tuple
    - v25
    - accepting: true
      player: eve
  - !!python/tuple
    - v26
    - accepting: true
      player: adam
  - !!python/tuple
    - v27
    - accepting: true
      player: adam
  - !!python/tuple
    - v28
    - accepting: true
      player: eve
  - !!python/tuple
    - v29
    - accepting: true
      player: eve
  - !!python/tuple
    - v30
    - accepting: true
      player: eve
  - !!python/tuple
    - v31
    - player: eve
  - !!python/tuple
    - v32
    - player: adam
  - !!python/tuple
    - v33
    - player: eve
  - !!python/tuple
    - v34
    - player: adam
  - !!python/tuple
    - v35
    - player: eve
  - !!python/tuple
    - v36
    - player: adam
  - !!python/tuple
    - v37
    - player: adam
  - !!python/tuple
    - v38
    - player: eve
  - !!python/tuple
    - v39
    - player: eve
  - !!python/tuple
    - v40
    - player: eve
