alphabet_size: 24
edges:
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - actions: north
    weight: 1
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - actions: west
    weight: 1
- !!python/tuple
  - (1, 1), right
  - (1, 2), right
  - actions: south
    weight: 1
- !!python/tuple
  - (1, 1), right
  - (2, 1), right
  - actions: east
    weight: 1
- !!python/tuple
  - (1, 2), right
  - (1, 1), right
  - actions: north
    weight: 1
- !!python/tuple
  - (1, 2), right
  - (1, 3), right
  - actions: south
    weight: 1
- !!python/tuple
  - (1, 2), right
  - (2, 2), right
  - actions: east
    weight: 1
- !!python/tuple
  - (1, 2), right
  - (1, 2), right
  - actions: west
    weight: 1
- !!python/tuple
  - (2, 1), right
  - (2, 1), right
  - actions: north
    weight: 1
- !!python/tuple
  - (2, 1), right
  - (2, 2), right
  - actions: south
    weight: 1
- !!python/tuple
  - (2, 1), right
  - (3, 1), right
  - actions: east
    weight: 1
- !!python/tuple
  - (2, 1), right
  - (1, 1), right
  - actions: west
    weight: 1
- !!python/tuple
  - (1, 3), right
  - (1, 2), right
  - actions: north
    weight: 1
- !!python/tuple
  - (1, 3), right
  - (1, 3), right
  - actions: south
    weight: 1
- !!python/tuple
  - (1, 3), right
  - (1, 3), right
  - actions: west
    weight: 1
- !!python/tuple
  - (1, 3), right
  - (2, 3), right
  - actions: east
    weight: 1
- !!python/tuple
  - (3, 1), right
  - (3, 1), right
  - actions: north
    weight: 1
- !!python/tuple
  - (3, 1), right
  - (3, 1), right
  - actions: east
    weight: 1
- !!python/tuple
  - (3, 1), right
  - (3, 2), right
  - actions: south
    weight: 1
- !!python/tuple
  - (3, 1), right
  - (2, 1), right
  - actions: west
    weight: 1
- !!python/tuple
  - (3, 2), right
  - (3, 1), right
  - actions: north
    weight: 1
- !!python/tuple
  - (3, 2), right
  - (3, 3), right
  - actions: south
    weight: 1
- !!python/tuple
  - (3, 2), right
  - (3, 2), right
  - actions: east
    weight: 1
- !!python/tuple
  - (3, 2), right
  - (2, 2), right
  - actions: west
    weight: 1
nodes:
- !!python/tuple
  - (1, 1), right
  - ap: empty_red_open
    init: true
    player: eve
- !!python/tuple
  - (1, 2), right
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - (2, 1), right
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - (1, 3), right
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - (2, 2), right
  - ap: lava_red_open
    player: eve
- !!python/tuple
  - (3, 1), right
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - (2, 3), right
  - ap: lava_red_open
    player: eve
- !!python/tuple
  - (3, 2), right
  - ap: empty_red_open
    player: eve
- !!python/tuple
  - (3, 3), right
  - accepting: true
    ap: goal_green_open
    player: eve
num_obs: 3
num_states: 9
start_state: (1, 1), right
