alphabet_size: 4
edges:
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
- !!python/tuple
  - (1, 1), right
  - (1, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (1, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (1, 2), right
  - (1, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (1, 2), right
  - (1, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (1, 2), right
  - (1, 2), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
- !!python/tuple
  - (1, 2), right
  - (2, 2), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (2, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (2, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (2, 1), right
  - (2, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (2, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
nodes:
- !!python/tuple
  - (1, 1), right
  - color: gray
    fillcolor: royalblue1
    is_accepting: false
    label: (1, 1), right
    observation: empty_red_open
    shape: box
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - 0
          - 1
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 2
          - 1
          - 0
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - &id002 !!python/object/apply:numpy.random._pickle.__randomstate_ctor
        args:
        - MT19937
        state:
          bit_generator: MT19937
          gauss: 0.0
          has_gauss: 0
          state:
            key: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - !!python/name:numpy.ndarray ''
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 624
              - !!python/object/apply:numpy.dtype
                args:
                - u4
                - 0
                - 1
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
              - false
              - !!binary |
                AAAAgNDUBj165EJbEKaoPni0hkZaHFyNasSCtgKNamoofoZj8yXF9BhDwMWkE/z5tEGqlQy3ahnQ
                Wlj5izyDA6pRZMz3CGHsgqL6tNEDqa86bwTe5KEi1oc8r93tR8VI5AUKnetOHf2DpptjDH0US/ll
                p/YONihrkNZYPLXPfSGeIZCxYuE0biIamuqwxIiJUQgvwCKVpMvm3o7OIInI6s/B4Qrix1ThXHEE
                aQrD0r3yUmzrDs7oRfmA8dGiqyrABgZIFfQx4tvS9ip9N3nPc36RwA9GTgDrF2S/fgyMpClfGDEG
                7zmZ0BH0iZ6RVgnSe6SldJloPw6rbeNZSp8COjVGu2ujgXV1vDGEc5L5KrL42QaMBZgD4Mt+IxfM
                XqSU1OV61SPKFXZNNZWsc+cr2s8U0YNm4AAVxJVM73cwf/L+xjCO94lhJq+A193hipmVhNW6gWtP
                rVFnMk+qyELg8IR6ahHpQx+d6SXxydozwnr1/quoDkIophbc3mHslySmDd4DXXi1LrMoHpDpIv8a
                f6se1b03eLE9P/RXt0hRoJcJ2yeF/NtKppMoy1MpofHwpCg6nKqLTFnMlcRx55Nv/f4DsAUD9hXX
                KG3Q47B7SIaA1j7X2x6dUrqZEshgDMjElIb692P0FXTCT1qSBrieX+PlPbaaWjybn+HXqtkEkWxp
                Y+dDfUSrr7Mdi+Q0/IwC74QRvBBvFtxEiKyU31u3JsvAZQN4UU7C4fc5t0IMGpzRdM8ufdEbwRjd
                kECbB5NCt0l58qxwOha+XMa8+wiDmhunJZAdNtuvdrNeuBsFM1Bi+oxE5NsSLhhbAOTPFtdKsqLs
                syMzBQzK6wKvacChtEF4T04nzXFc/9hHkrUcja+cjeKLGB+eH55v9tUMTeRkfFxS9WcH0e+CEtqw
                iQ5RKtcaSe3jPQXQZH5sNUN/yw4U21oir7W52Rzx5KSbZmOWDpewswNaRR0DlquiNcGdKgIXbJPq
                D5wk/YVlAWaP/vVRQo+UVLbyztENmYN2Qz64pXsr8EqqnFxvxVd5nRElkJotZPYYRx5djf9lvMvu
                o46g/Q7rSrV8y9cJDzo8ZGSHXYVDEPqTnMSqlyLjufaxPuxPImE+uaiIXn0mSs2FtYDoLNY+QY6H
                HppjspHUOvzy2LQ2fW00mxTZBsEgdTptVVJtDHlnrEG6zCIENaHmaVFrNGXdyF6eVjvQg4HZyuEs
                bjoQ08JRRLZopAB5do+eA9wD8j/k1lLpxcud/obTXhQg/b6HfF2a6VF+WaBwj/j7vN/y+8Yq0ImE
                BHxM5zEf0tF9b/q4kv6MR1DvOwxlpGuN/OOrV5QhVnIq6s3dXkVTNT7rb5baMIlbBBOhdz4/gBFH
                n/ldvItR1WHtIiKOmrrFgDt2tUqzH8FSKaToRYAGU8H9oLlCjxdsO7ThDj9WCSULO1Mb/30NKYmh
                Din8IbfDwA1h1WRDjElbMeF/yAewwhf8otceEZVz+FudU/V7npUBex1aVaxiPQ8l1pxdhN8X4km1
                Q89lPmThrE/AUgiosMa+EpmZzwqTbCvoLwUXHINY/VQ8g7qhGV9xC6skQ8v3fdkyOSmPg+3utfKu
                YHb6iVYX64PoZSc0wzz2fnf2ADHyf+VgBXbrDEz0AxG96Rs2d4iVup38hFMY+0bzQFtxX0YxpFjv
                LoLtSnX0voYmJs3fEwuzjxXVjNTE3MNJi8i8iDJ5eFOuq1eMb5pxHcn6idF3CPjC/v6UDHzhprHO
                l4MVLeH1FsNWv69nElDPCEZ4cWZqt1rRY559FvOr3aND8wY9SjHFp3b7+IP5gkv6oKZfmMfW7hDc
                qCSAOJmTsZ2wzl4hZL2S373mpabN0dW07aaz/CyWCu4hben8O93z4GG6bz3M3JpmbavVYBV5LTVr
                2BX/rAAqCYvb40wIDuAsDDQi1mD71vonk39csTRpWTsBpbmgW0ZNoUqpsneY/+Il1WvfTNpaDy0B
                1SPPkjcLrvoQ/yykauRjkcs06yJDdogb5q54+g7+UK/ITpFfCWypYHc3kGI212hLIFTmL65rRwDJ
                JKBKdtWedKbpONaATMI1PEnUqtLdMJzYLGVwDXlnRclCDsc40Cr58q1NIxX/JPg65l3WO4LH409C
                w/HL0EJljBru+nhgTSk1XZFs6TLnpdke9Eky5KlTgcy5l5EmrVRD1h/v6ZYLUROyptO+q+pVtEBZ
                CX/a8IA4qJJTWgMJ9AfOlkPAhpZDLo0PFTdarz/RNXlN/4mvX8dR1Rg9nc3H4yr3vEHQQcMZdUVS
                nRLY50Zcurpci6SSrN0Xbp8TDRBDra1Ku2rWQS5o3pkmFWKF3O1NkwsoJXGN6f4LVnyV2vvSDhJ4
                vSg/sPfKO1L9eTinomOtxRHpnaHvKopijf/ecVGdtUsfcldKB0pW8hu3TEmTFjUQG9ZOPunUy7wn
                kac/PUSXcpWLPlNJEplKtnrsZHVwTRYG3fBViHXOfWqSmlxoEcqHL3EACftmvR5sBI06m6nMb5jx
                P9lpC3gjLHsLlQajClWunKGEmzDsKGfr9rUuhN2ih7vdc/Z+X7bM17vZVuSushKHiD+t5xzfntBC
                rm84z76UIjhKee3XBT9KwmTCRPby5Y7R1ojKOBIrbjHwz8f6IbLeXtasGLKQMqyp4kGoy76cikFy
                rSRB3D6AMz44Td4LPO9cR5N8pNTOGyB1+2efEWmPYxeYr6M3+jq45G1cjvoZ9MO8eu4xpvseQZBD
                KD7+nwxtNHpTnuueL57R5AyZCvBw+piwNY9dQNjxdhRvW1lyLKX0e8x9lC/+meDFBgRg4n8z96gJ
                xAHjQnaME2Nf9UNuihbELERUUDigBlm4BH5LenhSwUMxa8b3lRl15JQS/83n1foLiBMWiifU/E2k
                a5ErOeP7IQ3p2xaiGDr3ZKGjd/DP2NCd6Ci2IcixROzC+qcwz9gtXMUX3DTyp4UhM18dfUUNn9dH
                MeY/eL6X/3GcU3FbOKQyLGGB0c8KNrkgG8mrMUh1WI0qVBPq9ZM61edqcsKAN9+fUuzfgvl8wAph
                eE/grRqegnJrjrXWpQwDkjI5ejU0MXy8aTLnB6d8cdAIHzCFplIe4VWqq7fP+smqmUlxCB2vdR0T
                R71/dxJBBvk5ISjsv7Qa4hL8zdsmvYurUSMj3TzVljL7/OsNc5sUMnVKoOOUmxMHYzl/YjCkxhNM
                Ozz3eN/iqy9FHKqEXBK55KGgZ1x/7bsx5S8VmDMkyTkBrKCwaKmD4I2r++WtW6nTEbzqH9L3jmPw
                SMaoQNWFg+2Yh/BvXjLPHGkvIpn3fK0kfmZPvvbs0HKse7+dFaBIqJTBL0l5
            pos: 623
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (1, 2), right
  - color: gray
    fillcolor: gray
    is_accepting: false
    label: (1, 2), right
    observation: empty_red_open
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 1
          - 2
          - 0
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - *id002
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (2, 1), right
  - color: gray
    fillcolor: gray
    is_accepting: false
    label: (2, 1), right
    observation: empty_red_open
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 0
          - 1
          - 2
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - *id002
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (2, 2), right
  - color: darkseagreen1
    fillcolor: lawngreen
    is_accepting: true
    label: (2, 2), right
    observation: goal_green_open
    peripheries: 2
    shape: doubleoctagon
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BAAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 4
        - - 1.0
      - *id002
    xlabel: '{goal_green_open}'
num_obs: 2
num_states: 4
start_state: (1, 1), right
