alphabet_size: 4
edges:
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (1, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
- !!python/tuple
  - (1, 1), right
  - (1, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (1, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (1, 2), right
  - (1, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (1, 2), right
  - (1, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (1, 2), right
  - (1, 2), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
- !!python/tuple
  - (1, 2), right
  - (2, 2), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (2, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: north
    probability: 0.25
    symbol: north
- !!python/tuple
  - (2, 1), right
  - (2, 1), right
  - fontcolor: blue
    label: east
    probability: 0.25
    symbol: east
- !!python/tuple
  - (2, 1), right
  - (2, 2), right
  - fontcolor: blue
    label: south
    probability: 0.25
    symbol: south
- !!python/tuple
  - (2, 1), right
  - (1, 1), right
  - fontcolor: blue
    label: west
    probability: 0.25
    symbol: west
nodes:
- !!python/tuple
  - (1, 1), right
  - color: gray
    fillcolor: royalblue1
    is_accepting: false
    label: (1, 1), right
    observation: empty_red_open
    shape: box
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - 0
          - 1
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 2
          - 1
          - 0
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - &id002 !!python/object/apply:numpy.random._pickle.__randomstate_ctor
        args:
        - MT19937
        state:
          bit_generator: MT19937
          gauss: 0.0
          has_gauss: 0
          state:
            key: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - !!python/name:numpy.ndarray ''
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 624
              - !!python/object/apply:numpy.dtype
                args:
                - u4
                - 0
                - 1
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
              - false
              - !!binary |
                AAAAgL/d0jd2DCh8FQxaMgJ7oGzTcL6EbgGARvbO+bdZfSsUDPthyw9jce6o7icaTXAPaZlHdNec
                eJJctbX65gHiE6xxAZxBy9VVrRhZV2V++pxcyUAkyvrd1NaAuI8HCkO4Pv8AEhZXWekHqdYmnCqj
                qGpZCDSKGc5XLoh9x/SzJOFdoxbOqktwlW+9+PL3TWlvZkPTLi/VOLu3KLAn6sVTN1tckzGRJG7a
                0LyjM7YmPOTcQgmvkU0SwynDjIwQcsfgssLmL7Q3jSklrFjjxTeuVVjnKAp6OKuWP1ikV8RYYmoX
                OFfVP2MtXVNmRultKDUqXK5fwz9DCY2eVg4ZdDEF4w3g+41/jkvQuuFFrvV8+d6HaPgFogo45ADK
                QMVLxfW31WiyBXhvchGMr2sgDVZKFGrgfQ2LrPiiDUyTA16nlrVLMwreUPZYaOHE/YvTPDje9Q2A
                4LBCfWzBYEpvm/LEQLBJaKRYaRXXaiPNrGlaRtjWMzFeWQgWRudr2CRDWi8Iv7eN2k9XdInUvTny
                uEYJZCdsdQFXzeOj4/508aAD+fHGpirLonXwi++uiSEOWLKarcn7JEVpj+cDyS6GAJSqBuaQI337
                +dvnMrzs82Mo/krjKj3HBYNILQ35lvbk2Bfq+3dLmiUD6j3ly4pEPwgbCqt44BV6Xg+QJ/r2tXrH
                nBWDYooPAAADXoExZH5G6wJJZ96As9TWqzgCC44EO1/mLbEbRnYWI4xdUxJTnYsU81bUbeKAkmOk
                bRIgFW9KTu5c2rWMWGxa68SRC3JEUvFLEz9475UFSK5mQ2JubY2rFxn8WTu0Dc4FcDVWsdknmdUb
                2kYSK3D8RLJWfQcyksS6lh0nOEpkfAailyv5ZKJ/cV3kHMZxmvRzmoJZg1bllDVmG+UuiAz6IgSi
                lREa6C5u7Mis3EGks7Q9eRXZWhlvuf2al896PRF9D1dHvgg/kXbzsnmolBqDoS0nwsbNQoZotItM
                T6HHYYtfO8WNSipzanGdkRf8hxiC1kuNd8LBDPDeHq8bwj/Xw4nA3WCSTHO70fdkkQkrDVvjcXcx
                eHZFbTdjj8ziJgoWdKb/B3BNHGlej8n8JCrOgsAFAEVPtLteqdV/EZLrJ++5xIcKyBhZWbuKQUas
                ptyZ8jekPqszcpfAjUsbpkseu6DqAUGOySoZqM/NpKA8LW9jTKgy55WpuvsEVHs5GYYJWJsTHVzQ
                qviIhJhZ9du39NmGZ2BomGypnsxJviQW4kscOglhhmK5DHuhHCXxu6qzJK2F+8qpegLoMKkyREpp
                encBRyIIUW/vDQQBz+xnCKamkfaA+f7Po/15884eQOR92qzB1U5MoVmjL8Q7qbF1Lbt36ZymVGj+
                unvMV6F9Q2kdbUY7CaVR7vOFfMgRfExUok/frNB1xZC3bShRRSEMAXIQ9E97azxIfqXMuiHq4iDs
                eFoXFZSHF5X1B4zqDAhAlqzppKbIaM6KNL/4UmIIiibVRIpLlf1HT9aD0W6HOa2HzxRPmzVJe8tm
                J5ZKBKN47Uz1I7qaXSQPKQ0oYNSF/1tcInFtTn1RX7LFb6jTPS1TTpKrnSGR/2PjPM5RjAlg97LV
                PVpIrtVs4UO8ruQtLaNCJLtrd0fs1eU8idEb3hHAraDC7z+7S9mBumlXC6GYD/BnnmgOb3dd/qjw
                RVi3IYmji20E5vLx8EztPIBMQ7WNbjBFf5815ef5HrZzcvMUrWEcDVMdu6AZ8s11oG+/ZFHoG24U
                BdHoo9w/N1I9FldopTfguHb9zb85ENP9ZQ50AE06KHUFhiyUXScdyoegFT44PZpyxG7ZjHgLL+Zv
                Na8bPxbrGdrhf1P3hUdoN1et6a5L9cTxdNP2N9/pspGTON0N4BOv2KAs8giTG/4JTdCTdPp3tcaT
                V7FVgs/vLSeASUTyh/2zK6bZ9Z4L88OoE1YwrOYjAf/cPa9+U5MtNDu6a0KgDf6kRTalSe6khkWz
                W95IkAd/XM4+v3HtnOWfVjFfwOTPRhYhJKH/ZBLKiYq3qRoglcUx7TPpiB3ldzq69NYsumNWWjGI
                gr0h0Ds8RWKztdX6VwyQrqmuacN9+48V4lylU0AblGl/XwUylcigtkPEiEuAGzpZQTW52ImA4Y7r
                l2LY3XlPawfRjzy/EyWN2xyyU+KnRUUN/kcTvV6hcJBD7kytaJraZe3UAKJa+uTeV0rYvJeZFfqR
                f/wNZ7Up8zBjf5ZmLzQU3ruzF4vVVfAjZmzdyuHoCEAmLTprngUrAIAPRibB1AO1QdgjrTpTvhq5
                leDJpAteGP/1xxV5m9hWHBnsxG9WWFzTsVH4HOayC7xEXceCpRpjyY4LkvU8z9Rc2+hfs21ELF7B
                lgOzPfcGc4mk3KDe6xmOdN79uTNEWWkWj3yuriwHRWrxM4JtBT6qcfYk64ZLrl/DlcgvJvGAmI/v
                6UCbYrKg34phtR/xxK5L1DzDfvmQf33ZulW0jn5yMSP+yOxXiRRkXkgF1rogJG9m3Bk+PvLcH3zJ
                OOdaFYUauFW35xn35Bp01G9qOseGSG4zdLFesTHcae/Koa1Sgh2Fz2ydPgHqbFgVjsuY4iStCa//
                ja+2m9sJLR9DOZs6lGJsD552BIVpvRf46Z3dDFI/67opO24zg53Ql151ntPRUcdMVQqW+XvxpGS6
                i3AcP88nUkXtpiJLSgYvqMQHDQjTQAZy6HovlzEMQzKW4Bxv1fIp8GNbaDYi6XYn6G0zIsuUl0aO
                CjtngRtMRUTvUaCfqLoKhUv2JjLIISb+rMKjy1CnIrYbPnY+H0BhZbkKNo5YNRp0bxOCc7t8teCh
                UO6zxiHU1+WtCH32ZGgU3K6TYu56DLSP2mKAjhmgOodgiC+aLSiIzzAi1uicVmoyX72FwyBB0UPj
                LrHhTa81l2XYfAMBUSBSJD9oEF3OSupKpdVCKmCdhN3pUQj2ZtEZsRZbe6eJF1BJPZvQVi6AZMjr
                bbv/eXfW1ju+7GdiVB5bUXdGWNRFtQ9YLZ7BgIG8SfNkMiVQO9tCNmDRvX+RcAp/+sHE89lz357n
                1bjrzsyFQz7zJfG0eDcVB2ffqfComeeTPH/uz2enCvPYF4Ye/eKyoga6pJygFs08FB36Tc4rwbBX
                XSWVV686NZMa7ewn8qgElfjXsBEI/I7QiN7ll5jYxRd4Bf2Y93UdrRAzIQW0SgowF9JiCSfkJzfv
                Gbuk96uWQWrzdqjmReYjt52gqMUn8efHZf+znN6kODB2uQovRQQiL3AXk/3+r2QEuhwZ6lb7chZQ
                QPecmm6Th/2fhI2L6e1tHwrNDaBViSZ3EZJoHX9cu558jSJgrFAQ3pTFFIqq
            pos: 623
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (1, 2), right
  - color: gray
    fillcolor: gray
    is_accepting: false
    label: (1, 2), right
    observation: empty_red_open
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 1
          - 2
          - 0
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - *id002
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (2, 1), right
  - color: gray
    fillcolor: gray
    is_accepting: false
    label: (2, 1), right
    observation: empty_red_open
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AwAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 3
          - 0
          - 1
          - 2
        - - 0.25
          - 0.25
          - 0.25
          - 0.25
      - *id002
    xlabel: '{empty_red_open}'
- !!python/tuple
  - (2, 2), right
  - color: darkseagreen1
    fillcolor: lawngreen
    is_accepting: true
    label: (2, 2), right
    observation: goal_green_open
    peripheries: 2
    shape: doubleoctagon
    style: filled
    trans_distribution: !!python/object/new:scipy.stats._distn_infrastructure.rv_sample
      state: !!python/tuple
      - a: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BAAAAAAAAAA=
        b: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BAAAAAAAAAA=
        badvalue: .nan
        extradoc: null
        inc: 1
        longname: null
        moment_tol: 1.0e-08
        name: transition
        seed: null
        shapes: null
        values: !!python/tuple
        - - 4
        - - 1.0
      - *id002
    xlabel: '{goal_green_open}'
num_obs: 2
num_states: 4
start_state: (1, 1), right
