alphabet_size: 9
edges:
- !!python/tuple
  - q0
  - q0
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (c)
      name: c
      symbol: c
    guard_formula: (c)
    prob: 0.8
    symbol: c
    weight: 0.2231435513142097
- !!python/tuple
  - q0
  - q1
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (a)
      name: a
      symbol: a
    guard_formula: (a)
    prob: 0.1
    symbol: a
    weight: 2.3025850929940455
- !!python/tuple
  - q0
  - q2
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (b)
      name: b
      symbol: b
    guard_formula: (b)
    prob: 0.1
    symbol: b
    weight: 2.3025850929940455
- !!python/tuple
  - q1
  - q1
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (a)
      name: a
      symbol: a
    guard_formula: (a)
    prob: 0.8
    symbol: a
    weight: 0.2231435513142097
- !!python/tuple
  - q1
  - q1
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (c)
      name: c
      symbol: c
    guard_formula: (c)
    prob: 0.1
    symbol: c
    weight: 2.3025850929940455
- !!python/tuple
  - q1
  - q3
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (b)
      name: b
      symbol: b
    guard_formula: (b)
    prob: 0.1
    symbol: b
    weight: 2.3025850929940455
- !!python/tuple
  - q2
  - q2
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (b)
      name: b
      symbol: b
    guard_formula: (b)
    prob: 0.8
    symbol: b
    weight: 0.2231435513142097
- !!python/tuple
  - q2
  - q2
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (c)
      name: c
      symbol: c
    guard_formula: (c)
    prob: 0.1
    symbol: c
    weight: 2.3025850929940455
- !!python/tuple
  - q2
  - q3
  - guard: !!python/object:src.spot.Parser.SymbolExpression
      formula: (a)
      name: a
      symbol: a
    guard_formula: (a)
    prob: 0.1
    symbol: a
    weight: 2.3025850929940455
nodes:
- !!python/tuple
  - q0
  - final_probability: 0.0
    init: true
    is_accepting: null
    trans_distribution: null
- !!python/tuple
  - q1
  - final_probability: 0.0
    is_accepting: null
    trans_distribution: null
- !!python/tuple
  - q2
  - final_probability: 0.0
    is_accepting: null
    trans_distribution: null
- !!python/tuple
  - q3
  - accepting: true
    final_probability: 1.0
    is_accepting: null
    trans_distribution: null
num_obs: 3
num_states: 4
start_state: q0
