# defines the final state probability needed for a state to be accepting
# (DEPRECATED)
beta: 0.90

# number of symbols in pdfa alphabet
alphabet_size: 5

# number of states in pdfa state space
num_states: 4

# symbol to use as the transition to a final state
final_transition_sym: '$'

# symbol to use as the empty (a.k.a. lambda) symbol
empty_transition_sym: 'lambda'

# unique start state string label of pdfa
start_state: 'q0'

# whether or not to smooth the input sym. transition distributions
smooth_transitions: False

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'q0':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q1':
    final_probability: 1.00
    trans_distribution: null
    is_accepting: True

  'q2':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

# define the edges of the graph
edges:

  # 'q0':
  #   'q0':
  #     formulas:
  #       - '!floor_green_open && !lava_red_open'
  #     probabilities:
  #       - 0.1

  #   'q1':
  #     formulas:
  #       - 'floor_green_open && !lava_red_open'
  #     probabilities:
  #       - 0.9

  'q0':
    'q0':
      formulas:
        - '!floor_green_open && !water_blue_open && !lava_red_open && !agent_blue_right'
      probabilities:
        - 0.8

    'q1':
      formulas:
        - 'floor_green_open && !lava_red_open && !agent_blue_right'
      probabilities:
        - 0.15

    'q2':
      formulas:
        - 'water_blue_open && !floor_green_open && !lava_red_open && !agent_blue_right'
      probabilities:
        - 0.05

  'q2':

    'q0':
      formulas:
        - 'carpet_yellow_open && !floor_green_open && !lava_red_open && !agent_blue_right'
      probabilities:
        - 0.4

    'q2':
      formulas:
        - '(water_blue_open || !carpet_yellow_open) && !floor_green_open && !lava_red_open && !agent_blue_right'
      probabilities:
        - 0.6
