# defines the final state probability needed for a state to be accepting
# (DEPRECATED)
beta: 0.90

# number of symbols in pdfa alphabet
alphabet_size: 5

# number of states in pdfa state space
num_states: 4

# symbol to use as the transition to a final state
final_transition_sym: '$'

# symbol to use as the empty (a.k.a. lambda) symbol
empty_transition_sym: 'lambda'

# unique start state string label of pdfa
start_state: 'q0'

# whether or not to smooth the input sym. transition distributions
smooth_transitions: False

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'q0':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q1':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q2':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q3':
    final_probability: 1.00
    trans_distribution: null
    is_accepting: null

# define the edges of the graph
edges:

  'q0':
    'q0':
      symbols:
        - 'c'
      probabilities:
        - 0.8

    'q1':
      symbols:
        - 'a'
      probabilities:
        - 0.1

    'q2':
      symbols:
        - 'b'
      probabilities:
        - 0.1

  'q1':

    'q1':
      symbols:
        - 'a'
        - 'c'
      probabilities:
        - 0.8
        - 0.1

    'q3':
      symbols:
        - 'b'
      probabilities:
        - 0.1

  'q2':

    'q2':
      symbols:
        - 'b'
        - 'c'
      probabilities:
        - 0.8
        - 0.1

    'q3':
      symbols:
        - 'a'
      probabilities:
        - 0.1
