alphabet_size: 32
edges:
- !!python/tuple
  - &id001 !!python/tuple
    - &id010 !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id001
  - &id002 !!python/tuple
    - &id011 !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: south
    strategy: true
    weight: -2
- !!python/tuple
  - *id001
  - &id003 !!python/tuple
    - &id012 !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - accept_all
  - accept_all
  - actions: north
    strategy: true
    weight: '0'
- !!python/tuple
  - T0_S2
  - T0_S2
  - actions: north
    strategy: true
    weight: '-4.0'
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id002
  - &id004 !!python/tuple
    - &id013 !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: south
    strategy: true
    weight: -2
- !!python/tuple
  - *id002
  - &id005 !!python/tuple
    - &id014 !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: south
    strategy: true
    weight: -2
- !!python/tuple
  - *id003
  - &id006 !!python/tuple
    - &id015 !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id004
  - &id007 !!python/tuple
    - &id016 !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: east
    strategy: true
    weight: -3
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id005
  - &id008 !!python/tuple
    - &id017 !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: east
    strategy: true
    weight: -3
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: south
    strategy: true
    weight: -2
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id007
  - &id009 !!python/tuple
    - &id018 !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: east
    strategy: true
    weight: -3
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: south
    strategy: true
    weight: -2
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id009
  - accept_all
  - actions: self
    strategy: true
    weight: 0
nodes:
- !!python/tuple
  - *id001
  - ap: empty_red_open
    dfa: T0_init
    init: true
    player: eve
    ts: *id010
- !!python/tuple
  - accept_all
  - accepting: true
- !!python/tuple
  - T0_S2
  - {}
- !!python/tuple
  - *id002
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id011
- !!python/tuple
  - *id003
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id012
- !!python/tuple
  - *id004
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id013
- !!python/tuple
  - *id005
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id014
- !!python/tuple
  - *id006
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id015
- !!python/tuple
  - *id007
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id016
- !!python/tuple
  - *id008
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id017
- !!python/tuple
  - *id009
  - ap: goal_green_open
    dfa: T0_init
    player: eve
    ts: *id018
num_obs: 3
num_states: 11
start_state: *id001
