alphabet_size: 92
edges:
- !!python/tuple
  - &id001 !!python/tuple
    - &id019 !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id001
  - &id002 !!python/tuple
    - &id020 !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id001
  - &id003 !!python/tuple
    - &id021 !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - accept_all
  - accept_all
  - actions: north
    player: eve
    weight: 0
- !!python/tuple
  - T0_S2
  - T0_S2
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id002
  - &id007 !!python/tuple
    - &id025 !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id002
  - &id008 !!python/tuple
    - &id026 !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id003
  - &id011 !!python/tuple
    - &id029 !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - &id004 !!python/tuple
    - &id022 !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 1
    - T0_init
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id004
  - &id005 !!python/tuple
    - &id023 !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id004
  - &id006 !!python/tuple
    - &id024 !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id005
  - &id009 !!python/tuple
    - &id027 !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id005
  - &id010 !!python/tuple
    - &id028 !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id006
  - &id012 !!python/tuple
    - &id030 !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 1
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id007
  - &id013 !!python/tuple
    - &id031 !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id008
  - &id015 !!python/tuple
    - &id033 !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id009
  - &id014 !!python/tuple
    - &id032 !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id010
  - &id016 !!python/tuple
    - &id034 !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 2
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 1
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id013
  - &id017 !!python/tuple
    - &id035 !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 3
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id014
  - &id018 !!python/tuple
    - &id036 !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 1
        - 3
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 0
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 1
    - T0_init
  - actions: north
    player: eve
    weight: -1
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 1
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 0
    - T0_init
  - actions: m
    player: adam
    weight: 0
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 3
      - 1
    - T0_init
  - actions: south
    player: eve
    weight: -1
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 3
        - 2
      - 1
    - T0_init
  - actions: east
    player: eve
    weight: -1
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - !!python/tuple
        - 2
        - 2
      - 1
    - T0_init
  - actions: west
    player: eve
    weight: -1
- !!python/tuple
  - *id017
  - accept_all
  - actions: self
    player: eve
    weight: 0
- !!python/tuple
  - *id018
  - accept_all
  - actions: self
    player: eve
    weight: 0
nodes:
- !!python/tuple
  - *id001
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id019
- !!python/tuple
  - accept_all
  - accepting: true
- !!python/tuple
  - T0_S2
  - {}
- !!python/tuple
  - *id002
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id020
- !!python/tuple
  - *id003
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id021
- !!python/tuple
  - *id004
  - ap: empty_red_open
    dfa: T0_init
    init: true
    player: eve
    ts: *id022
- !!python/tuple
  - *id005
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id023
- !!python/tuple
  - *id006
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id024
- !!python/tuple
  - *id007
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id025
- !!python/tuple
  - *id008
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id026
- !!python/tuple
  - *id009
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id027
- !!python/tuple
  - *id010
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id028
- !!python/tuple
  - *id011
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id029
- !!python/tuple
  - *id012
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id030
- !!python/tuple
  - *id013
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id031
- !!python/tuple
  - *id014
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id032
- !!python/tuple
  - *id015
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id033
- !!python/tuple
  - *id016
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id034
- !!python/tuple
  - *id017
  - ap: goal_green_open
    dfa: T0_init
    player: eve
    ts: *id035
- !!python/tuple
  - *id018
  - ap: goal_green_open
    dfa: T0_init
    player: eve
    ts: *id036
num_obs: 3
num_states: 20
start_state: *id004
