alphabet_size: 86
edges:
- !!python/tuple
  - T0_S2
  - T0_S2
  - actions: north
    weight: '-4.0'
- !!python/tuple
  - &id001 !!python/tuple
    - &id025 !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id001
  - &id002 !!python/tuple
    - &id026 !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id001
  - &id003 !!python/tuple
    - &id027 !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - accept_all
  - accept_all
  - actions: north
    weight: '0'
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id002
  - &id004 !!python/tuple
    - &id028 !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id002
  - &id005 !!python/tuple
    - &id029 !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id003
  - &id006 !!python/tuple
    - &id030 !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id004
  - &id007 !!python/tuple
    - &id031 !!python/tuple
      - (1, 4), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id004
  - &id008 !!python/tuple
    - &id032 !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id005
  - &id009 !!python/tuple
    - &id033 !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id006
  - &id010 !!python/tuple
    - &id034 !!python/tuple
      - (4, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id007
  - &id011 !!python/tuple
    - &id035 !!python/tuple
      - (1, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id007
  - &id012 !!python/tuple
    - &id036 !!python/tuple
      - (2, 4), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (1, 4), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (2, 4), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id008
  - &id013 !!python/tuple
    - &id037 !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (1, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id009
  - &id014 !!python/tuple
    - &id038 !!python/tuple
      - (4, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (4, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (4, 2), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id010
  - &id015 !!python/tuple
    - &id039 !!python/tuple
      - (5, 1), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (3, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - (1, 4), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - (1, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id011
  - &id016 !!python/tuple
    - &id040 !!python/tuple
      - (2, 5), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - (2, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id012
  - &id017 !!python/tuple
    - &id041 !!python/tuple
      - (3, 4), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id012
  - !!python/tuple
    - !!python/tuple
      - (1, 4), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (3, 4), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id013
  - &id018 !!python/tuple
    - &id042 !!python/tuple
      - (4, 3), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (2, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - (4, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - (4, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id014
  - &id019 !!python/tuple
    - &id043 !!python/tuple
      - (5, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id014
  - !!python/tuple
    - !!python/tuple
      - (3, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - (5, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - (5, 2), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id015
  - !!python/tuple
    - !!python/tuple
      - (4, 1), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - (2, 4), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - (2, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id016
  - &id020 !!python/tuple
    - &id044 !!python/tuple
      - (3, 5), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id016
  - !!python/tuple
    - !!python/tuple
      - (1, 5), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id017
  - !!python/tuple
    - !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id017
  - !!python/tuple
    - !!python/tuple
      - (3, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id017
  - &id021 !!python/tuple
    - &id045 !!python/tuple
      - (4, 4), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id017
  - !!python/tuple
    - !!python/tuple
      - (2, 4), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id018
  - !!python/tuple
    - !!python/tuple
      - (4, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id018
  - !!python/tuple
    - !!python/tuple
      - (4, 4), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id018
  - &id022 !!python/tuple
    - &id046 !!python/tuple
      - (5, 3), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id018
  - !!python/tuple
    - !!python/tuple
      - (3, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id019
  - !!python/tuple
    - !!python/tuple
      - (5, 1), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id019
  - !!python/tuple
    - !!python/tuple
      - (5, 3), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id019
  - !!python/tuple
    - !!python/tuple
      - (5, 2), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id019
  - !!python/tuple
    - !!python/tuple
      - (4, 2), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id020
  - !!python/tuple
    - !!python/tuple
      - (3, 4), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id020
  - !!python/tuple
    - !!python/tuple
      - (3, 5), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id020
  - &id023 !!python/tuple
    - &id047 !!python/tuple
      - (4, 5), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id020
  - !!python/tuple
    - !!python/tuple
      - (2, 5), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id021
  - T0_S2
  - actions: self
    weight: '-4.0'
- !!python/tuple
  - *id022
  - !!python/tuple
    - !!python/tuple
      - (5, 2), right
      - 0
    - T0_init
  - actions: north
    weight: -1
- !!python/tuple
  - *id022
  - &id024 !!python/tuple
    - &id048 !!python/tuple
      - (5, 4), right
      - 0
    - T0_init
  - actions: south
    weight: -2
- !!python/tuple
  - *id022
  - !!python/tuple
    - !!python/tuple
      - (5, 3), right
      - 0
    - T0_init
  - actions: east
    weight: -3
- !!python/tuple
  - *id022
  - !!python/tuple
    - !!python/tuple
      - (4, 3), right
      - 0
    - T0_init
  - actions: west
    weight: -4
- !!python/tuple
  - *id023
  - T0_S2
  - actions: self
    weight: '-4.0'
- !!python/tuple
  - *id024
  - T0_S2
  - actions: self
    weight: '-4.0'
nodes:
- !!python/tuple
  - T0_S2
  - {}
- !!python/tuple
  - *id001
  - ap: empty_red_open
    dfa: T0_init
    init: true
    player: eve
    ts: *id025
- !!python/tuple
  - accept_all
  - accepting: true
- !!python/tuple
  - *id002
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id026
- !!python/tuple
  - *id003
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id027
- !!python/tuple
  - *id004
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id028
- !!python/tuple
  - *id005
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id029
- !!python/tuple
  - *id006
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id030
- !!python/tuple
  - *id007
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id031
- !!python/tuple
  - *id008
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id032
- !!python/tuple
  - *id009
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id033
- !!python/tuple
  - *id010
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id034
- !!python/tuple
  - *id011
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id035
- !!python/tuple
  - *id012
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id036
- !!python/tuple
  - *id013
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id037
- !!python/tuple
  - *id014
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id038
- !!python/tuple
  - *id015
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id039
- !!python/tuple
  - *id016
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id040
- !!python/tuple
  - *id017
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id041
- !!python/tuple
  - *id018
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id042
- !!python/tuple
  - *id019
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id043
- !!python/tuple
  - *id020
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id044
- !!python/tuple
  - *id021
  - ap: lava_red_open
    dfa: T0_init
    player: eve
    ts: *id045
- !!python/tuple
  - *id022
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id046
- !!python/tuple
  - *id023
  - ap: lava_red_open
    dfa: T0_init
    player: eve
    ts: *id047
- !!python/tuple
  - *id024
  - ap: lava_red_open
    dfa: T0_init
    player: eve
    ts: *id048
num_obs: 3
num_states: 26
start_state: *id001
