graph:
  edges:
  - !!python/tuple
    - accept_all
    - accept_all
    - weight: '0'
  - !!python/tuple
    - &id001 !!python/tuple
      - &id021 !!python/tuple
        - s1
        - 0
      - T0_init
    - &id002 !!python/tuple
      - &id022 !!python/tuple
        - h12
        - '0'
      - T0_init
    - weight: '4'
  - !!python/tuple
    - *id001
    - &id003 !!python/tuple
      - &id023 !!python/tuple
        - h14
        - '0'
      - T0_init
    - weight: '2'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - !!python/tuple
        - s2
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - T0_S2
    - T0_S2
    - weight: '9'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - !!python/tuple
        - s4
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id004 !!python/tuple
      - &id024 !!python/tuple
        - s1
        - 1
      - T0_init
    - &id005 !!python/tuple
      - &id025 !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '4'
  - !!python/tuple
    - *id004
    - &id006 !!python/tuple
      - &id026 !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '2'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '2'
  - !!python/tuple
    - *id005
    - &id011 !!python/tuple
      - &id031 !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '3'
  - !!python/tuple
    - *id005
    - &id012 !!python/tuple
      - &id032 !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '4'
  - !!python/tuple
    - *id006
    - accept_all
    - weight: '9'
  - !!python/tuple
    - &id007 !!python/tuple
      - &id027 !!python/tuple
        - s2
        - 0
      - T0_init
    - &id008 !!python/tuple
      - &id028 !!python/tuple
        - h21
        - '0'
      - T0_init
    - weight: '2'
  - !!python/tuple
    - *id007
    - &id009 !!python/tuple
      - &id029 !!python/tuple
        - h23
        - '0'
      - T0_init
    - weight: '3'
  - !!python/tuple
    - *id007
    - &id010 !!python/tuple
      - &id030 !!python/tuple
        - h25
        - '0'
      - T0_init
    - weight: '4'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - !!python/tuple
        - s1
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - !!python/tuple
        - s3
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - !!python/tuple
        - s5
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '9'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '3'
  - !!python/tuple
    - *id012
    - T0_S2
    - weight: '3'
  - !!python/tuple
    - &id013 !!python/tuple
      - &id033 !!python/tuple
        - s3
        - 0
      - T0_init
    - &id014 !!python/tuple
      - &id034 !!python/tuple
        - h32
        - '0'
      - T0_init
    - weight: '9'
  - !!python/tuple
    - *id013
    - &id015 !!python/tuple
      - &id035 !!python/tuple
        - h34
        - '0'
      - T0_init
    - weight: '3'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - !!python/tuple
        - s2
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - !!python/tuple
        - s4
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id036 !!python/tuple
      - &id037 !!python/tuple
        - s4
        - 0
      - T0_init
    - accept_all
    - weight: '9'
  - !!python/tuple
    - &id016 !!python/tuple
      - &id038 !!python/tuple
        - h43
        - '0'
      - T0_init
    - !!python/tuple
      - !!python/tuple
        - s3
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id017 !!python/tuple
      - &id039 !!python/tuple
        - h41
        - '0'
      - T0_init
    - !!python/tuple
      - !!python/tuple
        - s1
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id018 !!python/tuple
      - &id040 !!python/tuple
        - h45
        - '0'
      - T0_init
    - !!python/tuple
      - !!python/tuple
        - s5
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id041 !!python/tuple
      - &id042 !!python/tuple
        - s5
        - 0
      - T0_init
    - T0_S2
    - weight: '3'
  - !!python/tuple
    - &id019 !!python/tuple
      - &id043 !!python/tuple
        - h54
        - '0'
      - T0_init
    - !!python/tuple
      - !!python/tuple
        - s4
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - !!python/tuple
        - s2
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - &id020 !!python/tuple
      - &id044 !!python/tuple
        - h52
        - '0'
      - T0_init
    - !!python/tuple
      - !!python/tuple
        - s2
        - 0
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - !!python/tuple
        - s1
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - !!python/tuple
        - s4
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - !!python/tuple
        - s5
        - 1
      - T0_init
    - weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - !!python/tuple
        - s3
        - 1
      - T0_init
    - weight: '0'
  vertices:
  - !!python/tuple
    - accept_all
    - accepting: true
  - !!python/tuple
    - *id001
    - ap: b
      dfa: T0_init
      init: true
      player: eve
      ts: *id021
  - !!python/tuple
    - *id002
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id022
  - !!python/tuple
    - T0_S2
    - {}
  - !!python/tuple
    - *id003
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id023
  - !!python/tuple
    - *id004
    - ap: b
      dfa: T0_init
      player: eve
      ts: *id024
  - !!python/tuple
    - *id005
    - ap: i
      dfa: T0_init
      player: eve
      ts: *id025
  - !!python/tuple
    - *id006
    - ap: g
      dfa: T0_init
      player: eve
      ts: *id026
  - !!python/tuple
    - *id007
    - ap: i
      dfa: T0_init
      player: eve
      ts: *id027
  - !!python/tuple
    - *id008
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id028
  - !!python/tuple
    - *id009
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id029
  - !!python/tuple
    - *id010
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id030
  - !!python/tuple
    - *id011
    - ap: r
      dfa: T0_init
      player: eve
      ts: *id031
  - !!python/tuple
    - *id012
    - ap: d
      dfa: T0_init
      player: eve
      ts: *id032
  - !!python/tuple
    - *id013
    - ap: r
      dfa: T0_init
      player: eve
      ts: *id033
  - !!python/tuple
    - *id014
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id034
  - !!python/tuple
    - *id015
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id035
  - !!python/tuple
    - *id036
    - ap: g
      dfa: T0_init
      player: eve
      ts: *id037
  - !!python/tuple
    - *id016
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id038
  - !!python/tuple
    - *id017
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id039
  - !!python/tuple
    - *id018
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id040
  - !!python/tuple
    - *id041
    - ap: d
      dfa: T0_init
      player: eve
      ts: *id042
  - !!python/tuple
    - *id019
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id043
  - !!python/tuple
    - *id020
    - ap: null
      dfa: T0_init
      player: adam
      ts: *id044
