alphabet_size: 87
edges:
- !!python/tuple
  - &id001 !!python/tuple
    - &id016 !!python/tuple
      - s1
      - 0
    - q0
  - &id008 !!python/tuple
    - &id002 !!python/tuple
      - h12
      - '0'
    - q2
  - actions: s12
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - *id001
  - &id015 !!python/tuple
    - &id009 !!python/tuple
      - h13
      - '0'
    - q2
  - actions: s13
    strategy: false
    weight: 2.3025850929940455
- !!python/tuple
  - &id003 !!python/tuple
    - *id002
    - q0
  - !!python/tuple
    - &id004 !!python/tuple
      - s2
      - 0
    - q0
  - actions: s12
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id003
  - !!python/tuple
    - &id006 !!python/tuple
      - s3
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id003
  - !!python/tuple
    - &id007 !!python/tuple
      - s1
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id005 !!python/tuple
    - *id002
    - q1
  - !!python/tuple
    - *id004
    - q1
  - actions: s12
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id005
  - !!python/tuple
    - *id006
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id005
  - !!python/tuple
    - *id007
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id008
  - !!python/tuple
    - *id004
    - q2
  - actions: s12
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id008
  - !!python/tuple
    - *id006
    - q2
  - actions: m
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id008
  - !!python/tuple
    - *id007
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id010 !!python/tuple
    - *id009
    - q0
  - !!python/tuple
    - &id011 !!python/tuple
      - s3
      - 0
    - q0
  - actions: s13
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id010
  - !!python/tuple
    - &id013 !!python/tuple
      - s1
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id010
  - !!python/tuple
    - &id014 !!python/tuple
      - s2
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id012 !!python/tuple
    - *id009
    - q1
  - !!python/tuple
    - *id011
    - q1
  - actions: s13
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id012
  - !!python/tuple
    - *id013
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id012
  - !!python/tuple
    - *id014
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id015
  - !!python/tuple
    - *id011
    - q2
  - actions: s13
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id015
  - !!python/tuple
    - *id013
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id015
  - !!python/tuple
    - *id014
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id017 !!python/tuple
    - *id016
    - q1
  - &id018 !!python/tuple
    - *id002
    - q3
  - actions: s12
    strategy: true
    weight: 0
- !!python/tuple
  - *id017
  - &id019 !!python/tuple
    - *id009
    - q3
  - actions: s13
    strategy: false
    weight: 0
- !!python/tuple
  - *id018
  - *id018
  - strategy: true
    weight: 0
- !!python/tuple
  - *id019
  - *id019
  - strategy: true
    weight: 0
- !!python/tuple
  - &id020 !!python/tuple
    - *id016
    - q2
  - !!python/tuple
    - *id002
    - q2
  - actions: s12
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id020
  - !!python/tuple
    - *id009
    - q2
  - actions: s13
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id021 !!python/tuple
    - *id016
    - q3
  - *id021
  - strategy: true
    weight: 0
- !!python/tuple
  - &id022 !!python/tuple
    - &id032 !!python/tuple
      - s1
      - 1
    - q0
  - &id028 !!python/tuple
    - &id023 !!python/tuple
      - s2
      - 1
    - q2
  - actions: s12
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - *id022
  - &id031 !!python/tuple
    - &id029 !!python/tuple
      - s3
      - 1
    - q2
  - actions: s13
    strategy: false
    weight: 2.3025850929940455
- !!python/tuple
  - &id024 !!python/tuple
    - *id023
    - q0
  - !!python/tuple
    - &id025 !!python/tuple
      - s1
      - 1
    - q1
  - actions: s21
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - *id024
  - !!python/tuple
    - &id027 !!python/tuple
      - s3
      - 1
    - q1
  - actions: s23
    strategy: false
    weight: 2.3025850929940455
- !!python/tuple
  - &id026 !!python/tuple
    - *id023
    - q1
  - !!python/tuple
    - *id025
    - q1
  - actions: s21
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id026
  - !!python/tuple
    - *id027
    - q1
  - actions: s23
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id028
  - !!python/tuple
    - *id025
    - q3
  - actions: s21
    strategy: true
    weight: 0
- !!python/tuple
  - *id028
  - !!python/tuple
    - *id027
    - q3
  - actions: s23
    strategy: false
    weight: 0
- !!python/tuple
  - &id069 !!python/tuple
    - *id029
    - q0
  - !!python/tuple
    - &id030 !!python/tuple
      - s1
      - 1
    - q0
  - actions: s31
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - &id070 !!python/tuple
    - *id029
    - q1
  - !!python/tuple
    - *id030
    - q1
  - actions: s31
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - *id031
  - !!python/tuple
    - *id030
    - q2
  - actions: s31
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - &id033 !!python/tuple
    - *id032
    - q1
  - &id034 !!python/tuple
    - *id023
    - q3
  - actions: s12
    strategy: true
    weight: 0
- !!python/tuple
  - *id033
  - &id035 !!python/tuple
    - *id029
    - q3
  - actions: s13
    strategy: false
    weight: 0
- !!python/tuple
  - *id034
  - *id034
  - strategy: true
    weight: 0
- !!python/tuple
  - *id035
  - *id035
  - strategy: true
    weight: 0
- !!python/tuple
  - &id036 !!python/tuple
    - *id032
    - q2
  - !!python/tuple
    - *id023
    - q2
  - actions: s12
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id036
  - !!python/tuple
    - *id029
    - q2
  - actions: s13
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id037 !!python/tuple
    - *id032
    - q3
  - *id037
  - strategy: true
    weight: 0
- !!python/tuple
  - &id038 !!python/tuple
    - &id053 !!python/tuple
      - s2
      - 0
    - q0
  - &id041 !!python/tuple
    - &id039 !!python/tuple
      - h21
      - '0'
    - q1
  - actions: s21
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - *id038
  - &id048 !!python/tuple
    - &id046 !!python/tuple
      - h23
      - '0'
    - q1
  - actions: s23
    strategy: false
    weight: 2.3025850929940455
- !!python/tuple
  - &id040 !!python/tuple
    - *id039
    - q0
  - !!python/tuple
    - &id042 !!python/tuple
      - s1
      - 0
    - q0
  - actions: s21
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id040
  - !!python/tuple
    - &id043 !!python/tuple
      - s3
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id040
  - !!python/tuple
    - &id044 !!python/tuple
      - s2
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id041
  - !!python/tuple
    - *id042
    - q1
  - actions: s21
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id041
  - !!python/tuple
    - *id043
    - q1
  - actions: m
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id041
  - !!python/tuple
    - *id044
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id045 !!python/tuple
    - *id039
    - q2
  - !!python/tuple
    - *id042
    - q2
  - actions: s21
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id045
  - !!python/tuple
    - *id043
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id045
  - !!python/tuple
    - *id044
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id047 !!python/tuple
    - *id046
    - q0
  - !!python/tuple
    - &id049 !!python/tuple
      - s3
      - 0
    - q0
  - actions: s23
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id047
  - !!python/tuple
    - &id050 !!python/tuple
      - s1
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id047
  - !!python/tuple
    - &id051 !!python/tuple
      - s2
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id048
  - !!python/tuple
    - *id049
    - q1
  - actions: s23
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id048
  - !!python/tuple
    - *id050
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id048
  - !!python/tuple
    - *id051
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id052 !!python/tuple
    - *id046
    - q2
  - !!python/tuple
    - *id049
    - q2
  - actions: s23
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id052
  - !!python/tuple
    - *id050
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id052
  - !!python/tuple
    - *id051
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id054 !!python/tuple
    - *id053
    - q1
  - !!python/tuple
    - *id039
    - q1
  - actions: s21
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id054
  - !!python/tuple
    - *id046
    - q1
  - actions: s23
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id055 !!python/tuple
    - *id039
    - q3
  - *id055
  - strategy: true
    weight: 0
- !!python/tuple
  - &id056 !!python/tuple
    - *id046
    - q3
  - *id056
  - strategy: true
    weight: 0
- !!python/tuple
  - &id057 !!python/tuple
    - *id053
    - q2
  - !!python/tuple
    - *id039
    - q3
  - actions: s21
    strategy: true
    weight: 0
- !!python/tuple
  - *id057
  - !!python/tuple
    - *id046
    - q3
  - actions: s23
    strategy: false
    weight: 0
- !!python/tuple
  - &id058 !!python/tuple
    - *id053
    - q3
  - *id058
  - strategy: true
    weight: 0
- !!python/tuple
  - &id071 !!python/tuple
    - &id066 !!python/tuple
      - s3
      - 0
    - q0
  - &id059 !!python/tuple
    - &id060 !!python/tuple
      - h31
      - '0'
    - q0
  - actions: s31
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id059
  - !!python/tuple
    - &id061 !!python/tuple
      - s1
      - 0
    - q0
  - actions: s31
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id059
  - !!python/tuple
    - &id063 !!python/tuple
      - s3
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id059
  - !!python/tuple
    - &id064 !!python/tuple
      - s2
      - 1
    - q0
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id062 !!python/tuple
    - *id060
    - q1
  - !!python/tuple
    - *id061
    - q1
  - actions: s31
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id062
  - !!python/tuple
    - *id063
    - q1
  - actions: m
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id062
  - !!python/tuple
    - *id064
    - q1
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id065 !!python/tuple
    - *id060
    - q2
  - !!python/tuple
    - *id061
    - q2
  - actions: s31
    strategy: true
    weight: 0.2231435513142097
- !!python/tuple
  - *id065
  - !!python/tuple
    - *id063
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - *id065
  - !!python/tuple
    - *id064
    - q2
  - actions: m
    strategy: false
    weight: 0.2231435513142097
- !!python/tuple
  - &id072 !!python/tuple
    - *id066
    - q1
  - !!python/tuple
    - *id060
    - q1
  - actions: s31
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - &id067 !!python/tuple
    - *id060
    - q3
  - *id067
  - strategy: true
    weight: 0
- !!python/tuple
  - &id073 !!python/tuple
    - *id066
    - q2
  - !!python/tuple
    - *id060
    - q2
  - actions: s31
    strategy: true
    weight: 2.3025850929940455
- !!python/tuple
  - &id068 !!python/tuple
    - *id066
    - q3
  - *id068
  - strategy: true
    weight: 0
- !!python/tuple
  - tmp_accp
  - tmp_accp
  - strategy: false
    weight: 0
nodes:
- !!python/tuple
  - *id001
  - ap: b
    dfa: q0
    player: eve
    ts: *id016
- !!python/tuple
  - *id003
  - ap: null
    dfa: q0
    player: adam
    ts: *id002
- !!python/tuple
  - *id005
  - ap: null
    dfa: q1
    player: adam
    ts: *id002
- !!python/tuple
  - *id008
  - ap: null
    dfa: q2
    player: adam
    ts: *id002
- !!python/tuple
  - *id010
  - ap: null
    dfa: q0
    player: adam
    ts: *id009
- !!python/tuple
  - *id012
  - ap: null
    dfa: q1
    player: adam
    ts: *id009
- !!python/tuple
  - *id015
  - ap: null
    dfa: q2
    player: adam
    ts: *id009
- !!python/tuple
  - *id017
  - ap: b
    dfa: q1
    player: eve
    ts: *id016
- !!python/tuple
  - *id018
  - ap: null
    dfa: q3
    player: eve
    ts: *id002
- !!python/tuple
  - *id019
  - ap: null
    dfa: q3
    player: eve
    ts: *id009
- !!python/tuple
  - *id020
  - ap: b
    dfa: q2
    player: eve
    ts: *id016
- !!python/tuple
  - *id021
  - ap: b
    dfa: q3
    player: eve
    ts: *id016
- !!python/tuple
  - *id022
  - ap: b
    dfa: q0
    player: eve
    ts: *id032
- !!python/tuple
  - *id024
  - ap: a
    dfa: q0
    player: eve
    ts: *id023
- !!python/tuple
  - *id026
  - ap: a
    dfa: q1
    player: eve
    ts: *id023
- !!python/tuple
  - *id028
  - ap: a
    dfa: q2
    player: eve
    ts: *id023
- !!python/tuple
  - *id069
  - ap: c
    dfa: q0
    player: eve
    ts: *id029
- !!python/tuple
  - *id070
  - ap: c
    dfa: q1
    player: eve
    ts: *id029
- !!python/tuple
  - *id031
  - ap: c
    dfa: q2
    player: eve
    ts: *id029
- !!python/tuple
  - *id033
  - ap: b
    dfa: q1
    player: eve
    ts: *id032
- !!python/tuple
  - *id034
  - ap: a
    dfa: q3
    player: eve
    ts: *id023
- !!python/tuple
  - *id035
  - ap: c
    dfa: q3
    player: eve
    ts: *id029
- !!python/tuple
  - *id036
  - ap: b
    dfa: q2
    player: eve
    ts: *id032
- !!python/tuple
  - *id037
  - ap: b
    dfa: q3
    player: eve
    ts: *id032
- !!python/tuple
  - *id038
  - ap: a
    dfa: q0
    init: true
    player: eve
    ts: *id053
- !!python/tuple
  - *id040
  - ap: null
    dfa: q0
    player: adam
    ts: *id039
- !!python/tuple
  - *id041
  - ap: null
    dfa: q1
    player: adam
    ts: *id039
- !!python/tuple
  - *id045
  - ap: null
    dfa: q2
    player: adam
    ts: *id039
- !!python/tuple
  - *id047
  - ap: null
    dfa: q0
    player: adam
    ts: *id046
- !!python/tuple
  - *id048
  - ap: null
    dfa: q1
    player: adam
    ts: *id046
- !!python/tuple
  - *id052
  - ap: null
    dfa: q2
    player: adam
    ts: *id046
- !!python/tuple
  - *id054
  - ap: a
    dfa: q1
    player: eve
    ts: *id053
- !!python/tuple
  - *id055
  - ap: null
    dfa: q3
    player: eve
    ts: *id039
- !!python/tuple
  - *id056
  - ap: null
    dfa: q3
    player: eve
    ts: *id046
- !!python/tuple
  - *id057
  - ap: a
    dfa: q2
    player: eve
    ts: *id053
- !!python/tuple
  - *id058
  - ap: a
    dfa: q3
    player: eve
    ts: *id053
- !!python/tuple
  - *id071
  - ap: c
    dfa: q0
    player: eve
    ts: *id066
- !!python/tuple
  - *id059
  - ap: null
    dfa: q0
    player: adam
    ts: *id060
- !!python/tuple
  - *id062
  - ap: null
    dfa: q1
    player: adam
    ts: *id060
- !!python/tuple
  - *id065
  - ap: null
    dfa: q2
    player: adam
    ts: *id060
- !!python/tuple
  - *id072
  - ap: c
    dfa: q1
    player: eve
    ts: *id066
- !!python/tuple
  - *id067
  - ap: null
    dfa: q3
    player: eve
    ts: *id060
- !!python/tuple
  - *id073
  - ap: c
    dfa: q2
    player: eve
    ts: *id066
- !!python/tuple
  - *id068
  - ap: c
    dfa: q3
    player: eve
    ts: *id066
- !!python/tuple
  - tmp_accp
  - accepting: true
    player: eve
num_obs: 3
num_states: 45
start_state: *id038
