alphabet_size: 39
edges:
- !!python/tuple
  - &id001 !!python/tuple
    - &id015 !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - &id002 !!python/tuple
    - &id016 !!python/tuple
      - (1, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id001
  - &id003 !!python/tuple
    - &id017 !!python/tuple
      - (1, 1), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id001
  - &id004 !!python/tuple
    - &id018 !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - accept_all
  - accept_all
  - weight: '0'
- !!python/tuple
  - *id002
  - &id005 !!python/tuple
    - &id019 !!python/tuple
      - (1, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id002
  - !!python/tuple
    - !!python/tuple
      - (1, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (1, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id003
  - !!python/tuple
    - !!python/tuple
      - (1, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id003
  - &id006 !!python/tuple
    - &id020 !!python/tuple
      - (1, 2), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id004
  - &id007 !!python/tuple
    - &id021 !!python/tuple
      - (2, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id004
  - &id008 !!python/tuple
    - &id022 !!python/tuple
      - (2, 1), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id004
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (1, 1), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (1, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id005
  - !!python/tuple
    - !!python/tuple
      - (1, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id006
  - &id009 !!python/tuple
    - &id023 !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id006
  - &id010 !!python/tuple
    - &id024 !!python/tuple
      - (1, 2), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id006
  - !!python/tuple
    - !!python/tuple
      - (1, 2), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id007
  - &id011 !!python/tuple
    - &id025 !!python/tuple
      - (2, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id007
  - !!python/tuple
    - !!python/tuple
      - (2, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (2, 1), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id008
  - !!python/tuple
    - !!python/tuple
      - (2, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id008
  - &id012 !!python/tuple
    - &id026 !!python/tuple
      - (2, 2), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id009
  - &id013 !!python/tuple
    - &id027 !!python/tuple
      - (1, 2), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id009
  - !!python/tuple
    - !!python/tuple
      - (1, 2), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id009
  - &id014 !!python/tuple
    - &id028 !!python/tuple
      - (2, 2), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (1, 2), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (1, 2), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id010
  - !!python/tuple
    - !!python/tuple
      - (1, 2), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - (2, 1), down
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - (2, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id011
  - !!python/tuple
    - !!python/tuple
      - (1, 1), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id012
  - accept_all
  - weight: 0
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (1, 2), left
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (1, 2), right
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id013
  - !!python/tuple
    - !!python/tuple
      - (1, 1), up
      - 0
    - T0_init
  - weight: 1
- !!python/tuple
  - *id014
  - accept_all
  - weight: 0
nodes:
- !!python/tuple
  - *id001
  - ap: empty_red_open
    dfa: T0_init
    init: true
    player: eve
    ts: *id015
- !!python/tuple
  - accept_all
  - accepting: true
- !!python/tuple
  - *id002
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id016
- !!python/tuple
  - *id003
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id017
- !!python/tuple
  - *id004
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id018
- !!python/tuple
  - *id005
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id019
- !!python/tuple
  - *id006
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id020
- !!python/tuple
  - *id007
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id021
- !!python/tuple
  - *id008
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id022
- !!python/tuple
  - *id009
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id023
- !!python/tuple
  - *id010
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id024
- !!python/tuple
  - *id011
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id025
- !!python/tuple
  - *id012
  - ap: goal_green_open
    dfa: T0_init
    player: eve
    ts: *id026
- !!python/tuple
  - *id013
  - ap: empty_red_open
    dfa: T0_init
    player: eve
    ts: *id027
- !!python/tuple
  - *id014
  - ap: goal_green_open
    dfa: T0_init
    player: eve
    ts: *id028
num_obs: 3
num_states: 15
start_state: *id001
